### ISSUE TITLE
Add active indicator to sidebar navigation

### ISSUE THREAD

**Issue by lukebennett88** [phirannodesigns/braillebarrier.com.au#1]
I'm writing this out for myself in the hope that I can 'rubber duck' myself into the answer, but if you have any ideas @mrhut10 please jump in!

I'm building out a small website, it's 1 page (plus a **success** page for the contact form and a **404** page.)

There is a fixed sidebar with the nav linking to different sections on the home page.
I have a class of 'active' that uses a pseudo-element to display an indicator next to the component that is active in the viewport.

I need to update this class when each component enters the viewport.

I think the best way to do this is probably to use the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver).

Here's how I see it working:

I've set up React context to keep track of all the items in the site navigation which is an array of objects that each have a key of `isActive`. I want to toggle this by running a function when each section component the viewport.

Run a `forEach()` on the array to set `isActive` to false on everything, and then update the the corresponding object to have `isActive` set to true.

I can't think of a concise way to do this. If I can't come up with a better way to do this, I think I'm going to:

Write the code to have the Intersection Observer check every component, and manually pass in the array index into the function to toggle `isActive`.

This feels gross, so I'm hoping I don't have to resort to this!

**Comment by mrhut10** [comment]
oh fun...

Appologies i had to stop when i did, hurt my wrist fencing and typing is killing.

hadn't used [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver) although I've heard of it being used heavely and can be a performance hit when scrolling, after reading the documentation thought would make a great use of hook. so found and went though [Justin Travis Waith-Mair
Justin Travis Waith-Mair Media article](https://medium.com/the-non-traditional-developer/how-to-use-an-intersectionobserver-in-a-react-hook-9fb061ac6cb5) which was excellent likewise had a lot of fun playing with his [sandbox](https://codesandbox.io/s/04vvrxj79p).

a forloop though the navigational items shouldn't be a huge performance cost so should be fine, and would need to fiddle with more before could come up with another idea, on my end will have to wait till tomorrow as think i need to go ice my wrist. lol.

p.s. note to self / look into tomorrow
- look into can alter the hook to ensure can still support multiple nodes/elements being sent to it,
- then make a wrapper component which puts all child components within the same observer
- then the observer will do a .reduce on the changes to find the navigational section being viewed.
- then the result will be stored on a useState thats stored on the page.
- the updated state will then change the alter the className field on the navigational sidebar

**Comment by mrhut10** [comment]
Did you put any more time on this one today? @lukebennett88 ?

**Comment by lukebennett88** [comment]
@mrhut10 only briefly, but I started getting some errors, and wasn't sure of the cause so I gave up and moved on to another project 😂

**Comment by mrhut10** [comment]
Spoken like a true Pro , lol.

I tried to pick up my laptop twice today but couldn't even type my password with my wrist, very frustrating!!

Hopefully there better in the night or at least tomorrow.

Do you get notifications if I don't tag you in comments btw? @lukebennett88

**Comment by lukebennett88** [comment]
There is a notifications button on the page that says I'm subscribed, so I should get notifications on this issue without being tagged.

**Comment by lukebennett88** [comment]
I just found this CodePen on CSS-Tricks: https://codepen.io/bramus/pen/ExaEqMJ
It looks like exactly what I'm trying to do albeit implemented in vanilla JS.
Hopefully this technique will convert to React nicely (I haven't done a lot with refs which I guess is the equivalent of using `document.querySelector()` right?

**Comment by lukebennett88** [comment]
React Waypoint might be useful for this:
https://www.npmjs.com/package/react-waypoint

**Comment by lukebennett88** [comment]
syedadeel2

**Comment by syedadeel2** [comment]
> Hi @syedadeel2
> Just adding a bit more context into this issue.
> I've created a CSS class called `active` in the `components.css` file. This will add the active indicator to the sidebar (which is in `header.js`) if the `isActive` value is set to true.
> All you need to do is write the code to change the `isActive` to true for the active component.
> Detecting which component is considered active might be a little tricky too, as it's possible to have more than one component in the viewport at one time since the products component is fairly short.
> Hope that all makes sense, please let me know if you have any questions.

@lukebennett88 looking to this and will fix this asap.

**Comment by syedadeel2** [comment]
@lukebennett88 working now

**Comment by syedadeel2** [comment]
@lukebennett88 done
